### ISSUE TITLE
Typo: replace Texte with Text

### ISSUE THREAD

**Issue by pcav** [epzt/GiSedTrend#1]
in the data tab

**Comment by epzt** [comment]
Done

**Comment by epzt** [comment]
Le 05/08/2015 14:54, Paolo Cavallini a écrit :

> in the data tab
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/epzt/GiSedTrend/issues/1.
> 
> Dear Paolo,

I made some changes.
Have a look to see if it fits QGIS plugin specs.
Thanks for your help

## 

Cordialement

/------------------------------------------------
_Emmanuel Poizot_
Cnam/Intechmer
B.P. 324
50103 Cherbourg Cedex

Web 1 : http://www.intechmer.cnam.fr
Web 2 : http://www.geoceano.fr
Phone (Direct) : (00 33)(0)233887342 ou 41

## Fax : (00 33)(0)233887339

/
Le Cnam/Intechmer http://www.intechmer.cnam.fr

/Ce message et toutes les pièces jointes sont confidentiels et établis à 
l'intention exclusive de son ou ses destinataires. Si vous avez reçu ce 
message par erreur, merci d'en avertir immédiatement l'émetteur et de 
détruire le message. Toute modification, édition, utilisation ou 
diffusion non autorisée est interdite. L'émetteur décline toute 
responsabilité au titre de ce message s'il a été modifié, déformé, 
falsifié, infecté par un virus ou encore édité ou diffusé sans 
autorisation.
This message and any attachments are confidential and intended for the 
named addressee(s) only.
If you have received this message in error, please notify immediately 
the sender, then delete the message. Any unauthorized modification, 
edition, use or dissemination is forbhide. Sender declin any 
responsabibility on this message if it has been modified, distorted, 
falsified, infected by virus or edited or broadcast without 
authorization. /

**Comment by pcav** [comment]
Thanks, please publish a new version.
